# Generated by Django 6.0.3 on 2026-04-06 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('min_radius_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_radius_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('base_delivery_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('surge_enabled', models.BooleanField(default=False)),
                ('pricing_reference_mode', models.CharField(choices=[('pharmacy_to_customer', 'Pharmacy To Customer'), ('city_center_to_customer', 'City Center To Customer')], default='pharmacy_to_customer', max_length=32)),
                ('city_center_latitude', models.FloatField(blank=True, null=True)),
                ('city_center_longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery_zones',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to='accounts.user')),
            ],
            options={
                'db_table': 'pharmacies',
            },
        ),
        migrations.CreateModel(
            name='PharmacyInventory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_available', models.BooleanField(default=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_updates', to='accounts.user')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='catalog.pharmacy')),
            ],
            options={
                'db_table': 'pharmacy_inventory',
                'indexes': [models.Index(fields=['pharmacy', 'drug_name'], name='pharmacy_in_pharmac_7a23d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('pharmacy', 'drug_name'), name='uq_pharmacy_drug_name')],
            },
        ),
    ]
